from environs import Env

__all__ = (
    'DATABASE',
    'COOKIES_LIVETIME',
    'TELEGRAM_BOT_TOKEN',
    'COOKIES_RENEWAL_DELAY',
    'CANCELED_ORDERS_DELAY',
    'STATISTICS_RENEWAL_DELAY',
    'DEPARTMENTS_RENEWAL_DELAY',
    'INGREDIENT_STOP_SALES_DELAY',
    'ALLOWED_STOP_SALES_THRESHOLD',
    'STOP_SALE_URGENCY_THRESHOLD',
    'TELEGRAM_NOTIFICATION_ATTEMPTS',
    'REPORT_NOTIFICATIONS_QUEUE',
    'PIZZERIA_SECTOR_STREET_STOP_SALES_DELAY',
)

env = Env()
env.read_env()

DATABASE = env.dict('DATABASE')
COOKIES_LIVETIME = env.int('COOKIES_LIVETIME')
TELEGRAM_BOT_TOKEN = env.str('TELEGRAM_BOT_TOKEN')
CANCELED_ORDERS_DELAY = env.int('CANCELED_ORDERS_DELAY')
COOKIES_RENEWAL_DELAY = env.int('COOKIES_RENEWAL_DELAY')
STATISTICS_RENEWAL_DELAY = env.int('STATISTICS_RENEWAL_DELAY')
DEPARTMENTS_RENEWAL_DELAY = env.int('DEPARTMENTS_RENEWAL_DELAY')
REPORT_NOTIFICATIONS_QUEUE = env.str('REPORT_NOTIFICATIONS_QUEUE')
INGREDIENT_STOP_SALES_DELAY = env.int('INGREDIENT_STOP_SALES_DELAY')
STOP_SALE_URGENCY_THRESHOLD = env.int('STOP_SALE_URGENCY_THRESHOLD')
ALLOWED_STOP_SALES_THRESHOLD = env.int('ALLOWED_STOP_SALES_THRESHOLD')
TELEGRAM_NOTIFICATION_ATTEMPTS = env.int('TELEGRAM_NOTIFICATION_ATTEMPTS')
PIZZERIA_SECTOR_STREET_STOP_SALES_DELAY = env.int('PIZZERIA_SECTOR_STREET_STOP_SALES_DELAY')
